### ISSUE TITLE
certain 'plot methods' yield "Error: Not a graph object"

### ISSUE THREAD

**Issue by jovo** [openconnectome/FlashR--#1]
including random, circle, and sphere.
maybe more.

**Comment by dmarchette** [comment]
Maybe fixed now.

On Sun, Jun 7, 2015 at 11:27 AM, joshua vogelstein <notifications@github.com

**Comment by jovo** [comment]
yup!

On Sun, Jun 7, 2015 at 1:41 PM, David Marchette notifications@github.com
wrote:

>  Maybe fixed now.
> 
> On Sun, Jun 7, 2015 at 11:27 AM, joshua vogelstein <
> notifications@github.com
> 
> > wrote:
> > 
> > Assigned #1 https://github.com/openconnectome/FlashR/issues/1 to
> > @dmarchette https://github.com/dmarchette.
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > https://github.com/openconnectome/FlashR/issues/1#event-324686069.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/FlashR/issues/1#issuecomment-109781244
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
