### ISSUE TITLE
check out reliability code

### ISSUE THREAD

**Issue by ebridge2** [openconnectome/FlashR--#27]
@shangsiwang

https://github.com/openconnectome/FlashR/tree/eric-dev2/R

see: reliability.R, nbinstar.R, distance.R

**Comment by jovo** [comment]
great! please document!

**Comment by ebridge2** [comment]
Code is documented in the manual (see the man folder). Do you want the
inputs/outputs above the functions as well?

**Comment by jovo** [comment]
ah, sorry, i should have clarified.
i want you to document using Roxygen2,
for which you write documentation in the code,
and then "compile" to automatically generate the man files.
does that make sense?

On Fri, Dec 4, 2015 at 10:17 AM, ebridge2 notifications@github.com wrote:

> Code is documented in the manual (see the man folder). Do you want the
> inputs/outputs above the functions as well?
> On Dec 3, 2015 6:33 PM, "joshua vogelstein" notifications@github.com
> wrote:
> 
> > great! please document!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/FlashR/issues/27#issuecomment-161824160>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/FlashR/issues/27#issuecomment-161991330
> .

## 

the glass is all full:  half water, half air.
neurodata.io

**Comment by ebridge2** [comment]
Ah yes, I remember you saying that now that you mention it. Will be done
tmr
ah, sorry, i should have clarified.
i want you to document using Roxygen2,
for which you write documentation in the code,
and then "compile" to automatically generate the man files.
does that make sense?

On Fri, Dec 4, 2015 at 10:17 AM, ebridge2 notifications@github.com wrote:

> Code is documented in the manual (see the man folder). Do you want the
> inputs/outputs above the functions as well?
> On Dec 3, 2015 6:33 PM, "joshua vogelstein" notifications@github.com
> wrote:
> 
> > great! please document!
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/FlashR/issues/27#issuecomment-161824160>
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/FlashR/issues/27#issuecomment-161991330
> 
> .

## 

the glass is all full: half water, half air.
neurodata.io

**Comment by jovo** [comment]
all good, thanks.

On Fri, Dec 4, 2015 at 1:51 PM, ebridge2 notifications@github.com wrote:

> Ah yes, I remember you saying that now that you mention it. Will be done
> tmr
> ah, sorry, i should have clarified.
> i want you to document using Roxygen2,
> for which you write documentation in the code,
> and then "compile" to automatically generate the man files.
> does that make sense?
> 
> On Fri, Dec 4, 2015 at 10:17 AM, ebridge2 notifications@github.com
> wrote:
> 
> > Code is documented in the manual (see the man folder). Do you want the
> > inputs/outputs above the functions as well?
> > On Dec 3, 2015 6:33 PM, "joshua vogelstein" notifications@github.com
> > wrote:
> > 
> > > great! please document!
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > <
> > 
> > https://github.com/openconnectome/FlashR/issues/27#issuecomment-161824160>
> > 
> > > .
> > 
> > —
> > Reply to this email directly or view it on GitHub
> > <
> > https://github.com/openconnectome/FlashR/issues/27#issuecomment-161991330
> > 
> > .
> 
> ## 
> 
> the glass is all full: half water, half air.
> neurodata.io
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openconnectome/FlashR/issues/27#issuecomment-162002275
> 
> > .
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/FlashR/issues/27#issuecomment-162049557
> .

## 

the glass is all full:  half water, half air.
neurodata.io
