### ISSUE TITLE
RDPG & Laplacian in 3D?

### ISSUE THREAD

**Issue by jovo** [openconnectome/FlashR--#3]
not sure how easy it is to embed 3D plots in shiny, 
and/or dynamically rotate them,
but if it is easy enough, i'd be interested in that functionality.

**Comment by dmarchette** [comment]
3D rotation is "easy" in shiny -- the library shinyRGL (plus the rgl
package) allows one to embed an RGL figure in the shiny app.
Basicall, all I'd need to to is set it up so that all layouts give 3d
layout vectors (or append a dummy third d on if they don't or whatever)
and condition on whether the 3d box is checked. I can do this quickly-ish,
so I'll put it high on the list.

Caveat -- sometimes, no matter what I do, things that plot in 3d just fine
suddenly stop not showing up in shiny apps. I think there is some subtle
Javascrip stuff going on.
So, when I say "easy" I mean either fairly trivial -- it will work
essentially immediately -- or it will drive me craze by not putting up any
plots.

We'll see.

**Comment by dmarchette** [comment]
Ok. I have a partial solution. Try it and see if it works. Basically, you
need shinyRGL and rgl, and if it works you will see (sometimes it takes a
while, even for a small graph, not sure what's going on) a point cloud you
can spin with the mouse.

At the moment, edges are not plotted. I will add this, if the thing works
well enough and consistently enough, but I have had some issues with
shinyRGL in the past, and it seemed kind of flaky today as well.

Anyway, let me know if it works, and if it doesn't. I probably won't get to
any changes until later next week or on the week end, so you have lots of
time to find lots of bugs.

dave

**Comment by jovo** [comment]
well, it works in safari for me, not in chrome, on my mac.
i think a little coordinate axis in the corner would help me "get my
bearings" a lot.
something like:
[image: Inline image 1]

in the meantime, this is already super awesome.

On Sun, Jun 7, 2015 at 3:40 PM, David Marchette notifications@github.com
wrote:

>  Ok. I have a partial solution. Try it and see if it works. Basically, you
> need shinyRGL and rgl, and if it works you will see (sometimes it takes a
> while, even for a small graph, not sure what's going on) a point cloud you
> can spin with the mouse.
> 
> At the moment, edges are not plotted. I will add this, if the thing works
> well enough and consistently enough, but I have had some issues with
> shinyRGL in the past, and it seemed kind of flaky today as well.
> 
> Anyway, let me know if it works, and if it doesn't. I probably won't get to
> any changes until later next week or on the week end, so you have lots of
> time to find lots of bugs.
> 
> dave
> 
> On Sun, Jun 7, 2015 at 3:10 PM, David Marchette dmarchette@gmail.com
> wrote:
> 
> > 3D rotation is "easy" in shiny -- the library shinyRGL (plus the rgl
> > package) allows one to embed an RGL figure in the shiny app.
> > Basicall, all I'd need to to is set it up so that all layouts give 3d
> > layout vectors (or append a dummy third d on if they don't or whatever)
> > and condition on whether the 3d box is checked. I can do this
> > quickly-ish,
> > so I'll put it high on the list.
> > 
> > Caveat -- sometimes, no matter what I do, things that plot in 3d just
> > fine
> > suddenly stop not showing up in shiny apps. I think there is some subtle
> > Javascrip stuff going on.
> > So, when I say "easy" I mean either fairly trivial -- it will work
> > essentially immediately -- or it will drive me craze by not putting up
> > any
> > plots.
> > 
> > We'll see.
> > 
> > On Sun, Jun 7, 2015 at 2:35 PM, joshua vogelstein <
> > notifications@github.com> wrote:
> > 
> > > Assigned #3 https://github.com/openconnectome/FlashR/issues/3 to
> > > @dmarchette https://github.com/dmarchette.
> > > 
> > > —
> > > Reply to this email directly or view it on GitHub
> > > https://github.com/openconnectome/FlashR/issues/3#event-324728652.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/openconnectome/FlashR/issues/3#issuecomment-109792265
> .

## 

the glass is all full:  half water, half air.
openconnecto.me, jovo.me, office hours
https://www.google.com/calendar/embed?src=e2ktu4lrgul8anp8hclrcminp8%40group.calendar.google.com&ctz=America/New_York
